version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Run linters
          command: npm run lint
      - run:
          name: Testing
          command: npm test
  publish_to_npm:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > $HOME/.npmrc
      - run: npm publish --access public
workflows:
  version: 2
  test:
    jobs:
      - test
      - publish_to_npm:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
